### ISSUE TITLE
Program doesn't launch when QT6 isn't installed on the system

### ISSUE THREAD

**Issue by dot-64** [StrataSource/sdk-launcher#2]
On version v0.4.0 the program refuses to launch if QT hasn't been installed on system.
To be more specfic I was having this issue on the Windows build, `SDKLauncher-p2ce-Windows-msvc-Release.zip`.

Attached screenshots of the specfic errors:

![Screenshot 2024-09-14_1](https://github.com/user-attachments/assets/69f35bf8-47a6-43e3-ab27-095c0bd16040) ![Screenshot 2024-09-14_2](https://github.com/user-attachments/assets/9eecc603-18a9-42fa-b914-a10e8818b999) ![Screenshot 2024-09-14_3](https://github.com/user-attachments/assets/b736f315-73c1-4df7-af47-6619e330ac50) ![Screenshot 2024-09-14_4](https://github.com/user-attachments/assets/4899cef8-91cc-46c9-b8b6-0669dc4c1722)

**Comment by craftablescience** [comment]
The program won't work without the Qt dlls, which are not included in the release since the release is meant to be bundled into P2CE at deployment time

**Comment by ozxybox** [comment]
Placing the executable in the p2ce bin win64 golder will allow it to run
